# Generated by Django 4.2.11 on 2024-05-17 09:14

import clerk_form.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2), clerk_form.models.validate_letters])),
                ('last_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2), clerk_form.models.validate_letters])),
                ('course', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2), clerk_form.models.validate_letters])),
                ('entry_scheme', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2), clerk_form.models.validate_letters])),
                ('intake', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2), clerk_form.models.validate_letters])),
                ('sponsorship', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=100)),
                ('date_of_birth', models.DateField(validators=[clerk_form.models.validate_age])),
                ('residence', models.CharField(max_length=255)),
            ],
        ),
    ]
